version: 2.1
jobs:
  build:
    docker:
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: nnote
          MYSQL_USER: root
          MYSQL_PASSWORD: password

    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
orbs:
  maven: circleci/maven@0.0.12
workflows:
  version: 2.1
  workflow:
    jobs:
    - build
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
